apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejsprog
  name: nodejsprog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejsprog
  template:
    metadata:
      labels:
        app: nodejsprog
    spec:
      containers:
      - image: victoryeo00/nodejsprog:latest
        name: nodejsprog
        ports:
        - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsprog-service
spec:
  type: LoadBalancer
  selector:
    app: nodejsprog
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
  