apiVersion: v1
kind: Pod
metadata:
   name: nodejsprog-pod
spec:
   containers:
   - name: nodejsprog-container01
     image: victoryeo00/nodejsprog:latest
     ports:
     - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: nodejsprog-pod
  labels:
    name: nodejsprog-pod
spec:
  type: NodePort
  ports:
    - port: 4002
      nodePort: 30036
      name: http
  selector:
    name: nodejsprog-pod